<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ADS-Coutinho')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('m2smart-home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;M2Smart-ADMIN</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        
                   
                        
                        <?php if ($this->UserIdentity('M2smartAdmin')): ?>
                        <li class="active"><a class="glyphicon glyphicon-th" href="<?php echo $this->url('m2smart-admin', array('controller' => 'setores')) ?>">Setores</a></li>
                        <li class="active"><a class="glyphicon glyphicon-heart" href="<?php echo $this->url('m2smart-admin', array('controller' => 'funcionarios')) ?>">Funcionarios</a></li>
                            <li class="active"><a class="glyphicon glyphicon glyphicon-user" href="<?php echo $this->url('m2smart-admin', array('controller' => 'usuarios')) ?>">Usuarios</a></li>
                            <li class="active"><a class="glyphicon glyphicon-off" href="<?php echo $this->url('m2smart-admin-logout') ?>">Logout</a></li>
               <?php endif; ?>
                    </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
        <?php echo $this->content; ?>
            <hr>
            <footer>
                <p class="glyphicon glyphicon-earphone" > (095)9136-3420 Wérnedres Coutinho de Souza</p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
