
<h4  class="alert alert-success"><em> Setores</em></h4>

<br/>
<p> <a class="btn btn-sm btn-success glyphicon " href="<?php echo $this->url('m2smart-admin', array('controller' => 'setores', 'action' => 'new')); ?>"><b><em>Novo Setor</em></b></a></p>

<table class="table table-striped">
    <thead>     
        <tr class="success">
            <th>Id</th>
            <th>Nome</th>
            <th>Editar</th>
            <th>Deletar</th>
        </tr>
    </thead>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId() ?></td>
            <td><?= $entity->getNome() ?></td>
            <td>
                <a  class="btn btn-info glyphicon glyphicon-list" href="<?php echo $this->url('m2smart-admin-interna', array('controller' => 'setores', 'action' => 'edit', 'id' => $entity->getId()));
        ?>">Editar</a></td>

            <td> 
                <a class="btn btn-danger  glyphicon glyphicon-trash" href="<?php
                   echo $this->url('m2smart-admin-interna', array('controller' => 'setores', 'action' => 'delete', 'id' => $entity->getId()));
                   ?>">Delete</a>

            </td>
        </tr>
    <?php endforeach; ?>

</table>