<h3><b><em>Novo Setor</em></b></h3>
<br/>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('m2smart-admin', array('controller' => 'setores ', 'action' => 'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br/>"."<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>