<h3>Editar Funcionarios</h3>

<br/>


<?php
$form = $this->form;

$form->setAttribute('action', $this->url('m2smart-admin-interna', array('controller' => 'funcionarios', 'action' => 'edit')));

$form->prepare();
echo $this->form()->openTag($form); 
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('profissao'));
echo $this->formRow($form->get('setor'));
echo $this->formRow($form->get('telefone'));
echo $this->formRow($form->get('salario'))."<br/>"."<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>