<h4 class="alert alert-success">Funcionarios</h4>
<br/>

<p> <a class="btn btn-sm btn-success glyphicon " href="<?php echo $this->url('m2smart-admin', array('controller' => 'funcionarios', 'action' => 'new')); ?>">Novo</a></p>


<table class="table table-striped">
    <thead>
        <tr class="success">
            <th>Id</th>
            <th>Nome</th>
            <th>Setor</th>
            <th>Telefone</th>
            <th>Salario</th>
            <th>Editar</th>
            <th>Deletar</th>
        </tr>
    </thead>
    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId() ?></td>
            <td><?= $entity->getNome() ?></td>
            <td><?= $entity->getSetor() ?></td>
            <td><?= $entity->getTelefone() ?></td>
            <td><?= $entity->getSalario() ?></td>

            <td>
                <a class="btn btn-info glyphicon glyphicon-list" href=" <?php echo $this->url('m2smart-admin-interna', array('controller' => 'funcionarios', 'action' => 'edit', 'id' => $entity->getId()));
        ?>">Editar</a></td>

            <td> 
                <a class="btn btn-danger  glyphicon glyphicon-trash" href="<?php
                   echo $this->url('m2smart-admin-interna', array('controller' => 'funcionarios', 'action' => 'delete', 'id' => $entity->getId()));
                   ?>">Deletar</a>

            </td>
        </tr>
    <?php endforeach; ?>

</table>