<h3>Editar Usuarios</h3>

<br/>


<?php
$form = $this->form;

$form->setAttribute('action', $this->url('m2smart-admin-interna', array('controller' => 'usuarios', 'action' => 'edit')));


$form->prepare();
echo $this->form()->openTag($form); 
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('senha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>